### ISSUE TITLE
C#: Inventory Controller + Items

### ISSUE THREAD

**Issue by jdetter** [boppygames/Community-Game#15]
This is mostly a C# implementation.

## class InventorySlot (no parent)

```C#
public class InventorySlot
{
  public Item item;
  public int count;
}
```

## class Item : ScriptableObject

This should have at least the following properties:

 - Item sprite
 - Item name
 - Item description
 - Item base price (this is modified when buying/selling)

Items like weapons, bows, etc. will inherit from Item to specify additional properties

## class InventoryController : NetworkBehaviour

The point of this class is to manage a list of inventory slots.

Methods:

 - `int AddItem(Item item, int count)`
   -  This adds an item to any available inventory slot, returns amount added
 - `int AddItem(Item item, int count, int slot)`
   -  This adds an item to the given slot, returns the amount added
 - `int RemoveItem(Item item, int count)`
   -  This removes items from any available inventory slot, returns amount removed
 - `int RemoveItem(Item item, int count, int slot)`
   -  This removes items from a specific slot, returns the amount removed
 - `InventorySlot GetSlot(int index)`
   -  Returns the inventory slot at the given position, null if no slot present
 - `int GetCount(Item item)`
   -  Returns the count of the given item in the inventory

**Comment by SeminixDev** [comment]
I'll put this under `Features/Inventory` for now. Let me know if you want that changed.

**Comment by SeminixDev** [comment]
Should I also make a test `InventoryItem` inheriting from `ScriptableObject`? It would store one in 'InventorySlot'.

**Comment by jdetter** [comment]
> Should I also make a test InventoryItem inheriting from ScriptableObject? It would store one in 'InventorySlot'.

Yes sorry this was supposed to be part of the description, I'll update it
