### ISSUE TITLE
UI Prefabs

### ISSUE THREAD

**Issue by jdetter** [boppygames/Community-Game#18]
We need the following prefabs to build up the UI:

 - [x] Button
 - [x] Panel
 - [x] Checkbox
 - [ ] ProgressBar
 - [x] Text
 - [x] Header
 - [x] DropDown

## Assets

- UI Skin

**Comment by NikoMix** [comment]
Do we already have a UI Design/Template we want to go with?

**Comment by jdetter** [comment]
> Do we already have a UI Design/Template we want to go with?
I just picked the best free UI skin I could find
